<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ktsu.Essentials" Version="2.8.0" />
    <PackageVersion Include="ktsu.Essentials.FileSystemProviders.Native" Version="2.8.0" />
    <PackageVersion Include="ktsu.Essentials.PersistenceProviders.ConfigHome" Version="2.8.0" />
    <PackageVersion Include="ktsu.Essentials.SerializationProviders.Json" Version="2.8.0" />
    <PackageVersion Include="ktsu.TrayApp" Version="1.2.0" />
    <PackageVersion Include="Polyfill" Version="11.4.2" />
  </ItemGroup>
</Project>
